name: nightly

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main

    - name: Checkout HTGDB Repo
      uses: actions/checkout@v2
      with:
        repository: frederic-mahe/Hardware-Target-Game-Database
        path: htgdb
        
    - name: Download SabreTools
      run: Invoke-WebRequest https://github.com/SabreTools/SabreTools/releases/download/1.1.1/SabreTools.v1.1.1.x86-64_net5.0.zip -OutFile "C:\sabretools.zip"
