name: nightly

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: htgdb-dat

    - name: Checkout HTGDB Repo
      uses: actions/checkout@v2
      with:
        repository: frederic-mahe/Hardware-Target-Game-Database
        path: htgdb
        
    - name: Download SabreTools
      run: Invoke-WebRequest https://github.com/SabreTools/SabreTools/releases/download/1.1.1/SabreTools.v1.1.1.x86-64_net5.0.zip -OutFile 'C:\sabretools.zip'
      
    - name: Extract SabreTools
      run: Expand-Archive -LiteralPath 'C:\sabretools.zip' -DestinationPath 'C:\sabretools'
      
    - name: Print Workspace Structure
      run: Tree $env:GITHUB_WORKSPACE /F | Select-Object -Skip 2
      
    - name: Remove Existing Dats
      run: Remove-Item "$env:GITHUB_WORKSPACE\htgdb-dat\dat\*" -Recurse -Force
      
    - name: Convert SMDBs
      run: C:\sabretools\SabreTools.exe -ud -ot=xml -out="$env:GITHUB_WORKSPACE\main\dats" -ef="item.status" "$env:GITHUB_WORKSPACE\htgdb\EverDrive Pack SMDBs\*"
      
